package limits

// Code generated by go-importconst DO NOT EDIT.
const CHAR_BIT = 8
const CHAR_MAX = 127
const CHAR_MIN = -128
const INT_MAX = 2147483647
const INT_MIN = -2147483648
const LONG_MAX = 2147483647
const LONG_MIN = -2147483648
const MB_LEN_MAX = 5
const SCHAR_MAX = 127
const SCHAR_MIN = -128
const SHRT_MAX = 32767
const SHRT_MIN = -32768
const UCHAR_MAX = 255
const ULONG_MAX = 4294967295
const USHRT_MAX = 65535
